import type { Profile } from './types';

export const DEFAULT_PROFILE: Profile = {
  version: 2,
  lastModified: new Date().toISOString(),
  basic: {
    nameZh: null,
    nameEn: null,
    nameUsed: null,
    gender: null,
    ethnicity: null,
    dateOfBirth: null,
    age: null,
    idType: null,
    idNumber: null,
    idCardValidFrom: null,
    idCardValidTo: null,
    politicalStatus: null,
    maritalStatus: null,
    hasChildren: null,
    hukouProvince: null,
    hukouCity: null,
    hukouType: null,
    currentProvince: null,
    currentCity: null,
    phone: null,
    email: null,
    emergencyContactName: null,
    emergencyContactPhone: null,
    emergencyContactRelation: null,
    heightCm: null,
    weightKg: null,
    expectedCity: null,
    expectedSalary: null,
    expectedPosition: null,
    availabilityDate: null,
    wechatId: null,
    qqId: null,
    linkedinUrl: null,
    githubUrl: null,
    personalWebsite: null,
  },
  education: [],
  experience: [],
  other: {
    languages: [],
    professionalSkills: [],
    certificates: [],
    familyMembers: [],
    selfEvaluation: null,
    careerPlan: null,
    strengths: null,
    weaknesses: null,
    driverLicense: null,
    isOverseasReturnee: null,
    covidVaccinationStatus: null,
    criminalRecord: null,
    hobbies: null,
    awards: [],
  },
  customFields: {},
};
